import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { sources } from './sources.mjs';
import { beats, routes, cases } from './data.mjs';
const root=fileURLToPath(new URL('.',import.meta.url));
const out=fileURLToPath(new URL('../dist/no-slop-engineer/',import.meta.url));
const archive=JSON.parse(await readFile(join(root,'conversation-links.json'),'utf8'));
let md='# The no slop engineer: source notebook\n\nResearch checked on 27 September 2026. This notebook keeps the reading separate from the proposed talk. Summaries are brief interpretations, not endorsements. Company results are self-reported unless the source says otherwise. Dates marked only 2026 were not pinned to an exact day in this pass.\n\n## Starting conversations\n\n- [Brainstorm No Slop Engineer](https://chatgpt.com/share/6ab8c9eb-a52c-83eb-836e-296426a7a647?ogimg=plain)\n- [Find reputable AI engineering sources](https://chatgpt.com/share/6ab8ca1b-fd08-83ed-8b94-507df0d51356?ogimg=plain)\n\nBoth conversations were read from their public page data. Their search-result caches also contain irrelevant links; the archive below preserves their 42 actual citation destinations, not the whole search cache.\n\n## Corrections and limits\n\n- The interview is Dillon Mulroy. John Fawcett is a separate practitioner whose post was initially suggested in error.\n- Niall Murphy links to Aidan Harding\'s July 2026 Putting Learning in the Loop. The earlier chat instead named the September 2025 Coding with AI post. Both are retained here.\n- incident.io\'s DevEx article and Anthropic\'s long-running-agent article are from 2025. They are useful background, not recent summer 2026 evidence.\n- Spotify keeps its existing thresholds. Its discussion does not establish that large PRs are safe.\n- The newer Polylane production-review post is the main production reference. Its forecast is experimental; a plausible failure can lack confirming telemetry. Its prevented-incident metric is an operational proxy, not direct observation of an incident that would otherwise have happened.\n- The Jev follow-up is an optional aside about bounded decisions. It is separate from the time-series forecasting model.\n- USENIX and Signals pages are saved for later viewing. Their recordings were not watched in this pass. Boris Cherny\'s profile feed supports the described routine, but a stable post permalink and date are still needed for stage-ready attribution.\n- Kiro\'s supplied planning URL redirects. Recheck specific product claims before using them.\n\n';
for(const group of [...new Set(sources.map(s=>s.group))]){md+=`## ${group}\n\n`;for(const s of sources.filter(s=>s.group===group)){md+=`### ${s.title}\n\n[${s.author}](${s.url}) · ${s.date}\n\n${s.take}\n\nLimit: ${s.caution}\n\n`;}}
md+='## Original citation destinations\n\nThese preserve every distinct destination attached to a citation in either shared conversation. Some are duplicates of the reading list; some are background leads. Inclusion here does not mean a page or recording was fully reviewed. The original Sourcegraph test hostname is preserved; use the canonical source in the annotated list above.\n\n';
for(const a of archive)md+=`- [${(a.title||a.url).replace(/[\[\]\n]/g,' ')}](${a.url}) · conversation ${a.conversations.join(', ')}\n`;
md+='\n## Additional related links retained\n\n- [Chopin repository](https://github.com/githubnext/chopin)\n- [Spec Kit documentation](https://github.github.io/spec-kit/)\n- [Pasi: browser verification for coding agents](https://www.huuhka.net/browser-verification-for-coding-agents-chrome-devtools-mcp-vs-agent-browser/)\n- [Pasi: primary vs subagents](https://www.huuhka.net/primary-vs-subagents-in-llm-harnesses/)\n- [Cat Hicks: learning opportunities](https://github.com/DrCatHicks/learning-opportunities)\n- [Simon Willison: automated tests](https://simonwillison.net/2025/May/28/automated-tests/)\n- [Original Addy Osmani outer-loop URL](https://addyosmani.com/blog/own-the-outer-loop/)\n- [Boris Cherny maintenance post lead](https://x.com/bcherny/status/2088014489438621990) · permalink lead; not independently reviewed here\n';
await writeFile(join(root,'sources.md'),md);
let outline='# The no slop engineer\n\nProposed base, 27 September 2026. No Slidev deck or demo application yet.\n\nAudience: mid-to-senior engineers.\n\n60-minute slot: 52 minutes of material, including 14 minutes of demos, plus 3 minutes of demo flexibility and 5 minutes of questions. About 18 slides plus demo screens. These timings need rehearsal.\n\n## Recommendation\n\nFollow one change all the way through. Show the decisions and the evidence that change it. Compare this with the workflow-led and debate-led alternatives in the HTML workbench.\n\nUse a small task-export teaching fixture unless an actual Bun Do development episode gives us a stronger story. A real episode is preferable when it can be explained and reproduced quickly.\n\n';
let start=0;for(const id of routes.case.order){const b=beats[id];outline+=`## ${start} to ${start+b.minutes} minutes: ${b.title}\n\nQuestion: ${b.question}\n\nExhibit: ${b.exhibit}\n\nSpeaker notes: ${b.note}\n\nRisk: ${b.risk}\n\n`;start+=b.minutes;}
outline+='## Production example\n\nUse Polylane\'s September 21 production-review post. Explain the connection between the diff, affected resources and production telemetry. Distinguish observations from failure hypotheses and experimental impact forecasts. Give the policy for unconfirmed but plausible failures an explicit place.\n\nJev is an optional 30-second aside, disabled in the default plan. Adding it makes the default total 60.5 minutes, so trim elsewhere. It is for decision tasks, not the time-series forecast.\n\n## Proposed case contract\n\n';const c=cases.export;outline+=`${c.pitch}\n\nDecision: ${c.decision}\n\nEvidence: ${c.proof}\n\nNegative control: ${c.boundary}\n\nOut of scope: ${c.exclude}\n\nPreparation: ${c.prep}\n\n## Risks to resolve next\n\n- Select a real episode or explicitly label the seeded teaching defect.\n- Rehearse the bad/good transition and show that the check detects the original error.\n- Keep the software-factory counterargument fair without turning the talk into a company survey.\n- Keep the production segment concrete. The export case is strongest on authorization; retention is stronger on operational impact.\n- Preserve five minutes for questions. Use prepared artifacts when a live agent run stalls.\n\n## Discussion\n\nWhich development episode would you most like to tell? What should the audience disagree with? Which operation deserves human inspection even when the checks are strong?\n\nSee [the source notebook](sources.md) for the reading and original links.\n`;
await writeFile(join(root,'outline.md'),outline);
await mkdir(out,{recursive:true});
for(const name of ['index.html','stories.html','style.css','app.mjs','data.mjs','sources.mjs','sources.md','outline.md','conversation-links.json'])await copyFile(join(root,name),join(out,name));
console.log(`Built ${out}\n${sources.length} annotated sources; ${archive.length} original citation destinations.`);
