export const beats = {
 hook: {title:'Would you ship this?', short:'The problem', minutes:4, slides:'2', demo:0, color:'ink', question:'What would convince you this change is safe?', exhibit:'A plausible feature, a green check, and one unanswered behavior question.', note:'Define slop operationally: a change accepted without adequate evidence about its behavior and consequences. This is a proposed definition for the talk. Human code can qualify too. Give the audience twenty seconds to predict the failure before showing the answer. Keep workflow history to one sentence or one backup slide.', risk:'Opening with a cartoonishly bad agent makes the rest too easy. The first result should look reasonable.', refs:['pasi-flow','niall'], stages:['A plausible change','Audience predicts','One unanswered question']},
 research: {title:'Find the facts that change the decision',short:'Research',minutes:6,slides:'2',demo:3,color:'teal',question:'What do we know, and what are we assuming?',exhibit:'A request path with one surprising boundary, plus a short facts / decisions / unknowns sheet.',note:'Do not rehearse library trivia. Research should reduce uncertainty about this change. Have the agent trace the existing path and show one finding that alters the plan. Ask a question you need answered, then verify the relevant code or documentation yourself.',risk:'A polished research summary can conceal an invented fact. Follow one claim back to its source.',refs:['pasi-rpi','chopin'],stages:['Trace the current path','Mark an assumption','Follow the evidence']},
 plan: {title:'Make the plan lose an argument',short:'Intent',minutes:8,slides:'3',demo:3,color:'teal',question:'What must remain true when the happy path fails?',exhibit:'The vague request becomes two explicit acceptance examples and one excluded behavior.',note:'Let the audience supply the missing condition before the agent offers its default. Record the decision and the evidence it needs. Add one minute on Chopin and Spec Kit as signs of attention moving upstream. A markdown file is useful only if somebody challenges it.',risk:'The planning artifact can become the next kind of slop. Keep only decisions that change implementation or verification.',refs:['pasi-rpi','honey-review','aidan-learning'],stages:['The original request','A failure condition','A decision and an exclusion']},
 slice: {title:'Keep the change inside your understanding',short:'Slices',minutes:6,slides:'2',demo:0,color:'teal',question:'Can each unit be explained, exercised and reviewed?',exhibit:'Three vertical behavior slices with a visible acceptance condition for each.',note:'Distinguish a review unit from a deployment unit. A stack can reduce review size while the full feature still needs an integration check. Do not split solely into database, service and UI layers. Treat 300 to 800 lines as Dillon\'s example, not a quota. A ten-line authorization change can deserve more attention than a large mechanical edit.',risk:'Many tiny PRs can increase coordination cost. Pick meaningful behavior boundaries, not arbitrary line counts.',refs:['dillon','stack','spotify'],stages:['One large proposal','Behavior boundaries','Evidence on each slice']},
 verify: {title:'Green is a starting point',short:'Evidence',minutes:12,slides:'3',demo:5,color:'red',question:'Which claim did we actually test?',exhibit:'A green happy-path test beside a failing boundary check, followed by the corrected behavior.',note:'Use a prepared incorrect implementation and label it as seeded. A review agent proposes a concrete failure mechanism. Reproduce it independently, fix it, run the same check again, then deliberately reintroduce the bug to show the regression check fails. The independent expected result matters more than a second model agreeing.',risk:'Writing implementation and tests from the same mistaken assumption can make both agree. A passing browser flow cannot prove every hidden property.',refs:['stripe','openai','anthropic'],stages:['Happy path passes','Boundary check fails','Fix, rerun, reintroduce']},
 loop: {title:'Show the loop, including the stop',short:'Bounded loops',minutes:7,slides:'2',demo:3,color:'red',question:'What happens after repeated failure or a newer commit?',exhibit:'Step through trigger → inspect → bounded fix → check → accept, retry or stop.',note:'Start with a local review-and-fix loop. Then replace the trigger with a PR comment or CI result. Show commit identity, handled feedback, attempt budget and escalation. Allow at most two fixes in the demonstration. Ordinary code owns scheduling and state; the model interprets a finding. Avoid a whole agent orchestration framework.',risk:'"Until all reviewers agree" can burn time, oscillate or converge on the wrong answer. A stale CI result must not authorize a newer commit.',refs:['pasi-review','incident','sourcegraph'],stages:['Local review trigger','One bounded retry','Stop or wait for fresh evidence']},
 production: {title:'What could change our minds?',short:'Beyond merge',minutes:6,slides:'3',demo:0,color:'ochre',question:'When could stronger checks replace some human inspection?',exhibit:'Honeycomb / Intercom / Spotify compared, then one production signal linked back to a test.',note:'Give the counterargument a fair hearing. OpenAI and Uber already automate substantial workflows. Intercom selects changes for auto-approval; Spotify explicitly has not relaxed its size thresholds. Distinguish prevention from detection and recovery. Ask what telemetry is missing, and who owns the result if a plausible failure is unconfirmed.',risk:'Company anecdotes are not controlled comparisons. A rollback may be unsafe after a data migration. Do not promise zero incidents.',refs:['honey-review','intercom','spotify','uber','poly-prod'],stages:['Different operating models','Evidence and missing evidence','One learned constraint']},
 close: {title:'Leave with one change to make on Monday',short:'Takeaway',minutes:3,slides:'1',demo:0,color:'ink',question:'Which recurring correction could your repo check?',exhibit:'The original feature request, now connected to a decision, a small diff and a repeatable check.',note:'Ask the audience to name one missing behavioral check or repeated review comment. Keep a human owner for the decision. End on the artifact chain we built, with sources available separately.',risk:'A checklist without the case-study evidence feels like familiar advice. Reuse the actual artifacts.',refs:['pasi-review','openai'],stages:['Return to the request','Show the evidence chain','Choose one repo improvement']}
};
export const routes = {
 case: {label:'One change, all the way through',tag:'Recommended',summary:'Open on a plausible change. Return to it whenever a decision or a check improves it.',strength:'The audience sees what each practice changes. The demos have a reason to exist.',cost:'Needs a carefully rehearsed example. A contrived failure will undermine the argument.',order:['hook','research','plan','slice','verify','loop','production','close'],times:{}},
 workflow: {label:'The engineering workflow',tag:'Most direct',summary:'Build the research, plan, implement and verify model, then demonstrate it in one continuous run.',strength:'Easy to follow and easy to adapt into your existing deck.',cost:'Can feel like a methods lecture. The payoff arrives late; reserve the full verification demo.',order:['hook','research','plan','slice','loop','verify','production','close'],times:{research:7,plan:7,production:4}},
 debate: {label:'Who still needs to understand?',tag:'More provocative',summary:'Start with competing team practices, take a position, then test it against the same feature.',strength:'Fits experienced engineers and gives counterevidence real weight.',cost:'Risks becoming a literature review. Company comparisons must stay short and contextual.',order:['hook','production','slice','research','plan','verify','loop','close'],times:{production:9,research:5,plan:6,loop:6}}
};
export const cases = {
 export: {label:'Export my team\'s tasks',tag:'Recommended teaching case',pitch:'A small team-task app adds a CSV export. The obvious implementation works; a tenant boundary does not.',why:'A visible result, familiar business behavior, and a boundary that a unit test can easily miss. Browser, API and data checks each have a job.',risk:'This is a proposed teaching fixture, not a claimed production incident. Seed and disclose the missing tenant filter. Keep CSV escaping as an optional second defect.',prep:'Estimate 1 to 2 working days for a minimal fixture, bad/good commits, regression check and recordings. Not built yet.',facts:['Two fictional teams share storage.','Authentication establishes the caller and team.','The table view already applies a team filter.','The new export path bypasses that filter.'],decision:'Only tasks belonging to the authenticated team may appear in an export, regardless of query parameters.',exclude:'No background export queue, large-file streaming, new identity system or spreadsheet formatting.',slices:['Own-team export end to end, behind a flag.','Enforce the boundary and verify with two seeded teams.','Exercise the UI and add a redacted export-count signal.'],proof:'Team A exports exactly its two seeded rows. Team B\'s canary row never appears. A forged team identifier does not widen access.',boundary:'The seeded regression fails when the tenant predicate is removed.',telemetry:'A per-team export count and correlation ID support investigation. They cannot prove isolation by themselves.',prompts:['Trace how the task list derives the current team. Show where the query is scoped and where an export could bypass it. Separate facts from assumptions.','Propose the smallest export change. State the tenant invariant, the negative example, excluded work, and how each slice can be verified.','Review the export against the stated invariant. Give a reproducible request and expected result for any finding. Do not accept test count as evidence.']},
 bundo: {label:'Bun Do after an offline edit',tag:'Most personal',pitch:'Make an offline task edit, reconnect, and show what happens when an account or shared task has changed.',why:'Your own application gives the talk an authentic history. The repo describes offline edits, synchronization and account-isolated storage.',risk:'Android, sync and sign-in add setup and demo risk. We have not selected or verified a historical defect. Use an actual development episode if you have one.',prep:'Estimate 2 to 4 days to isolate a real episode, prepare accounts, capture recordings and rehearse recovery. Discovery may change this.',facts:['The app supports offline everyday edits.','Accounts must retain separate local data.','Sync introduces retries and stale state.','A specific historical change still needs selection.'],decision:'Proposed invariant: a queued edit created under account A must never be replayed as account B. Confirm against the app\'s actual contract.',exclude:'No full sync architecture lecture, real household data, live cloud sign-in or emulator installation on stage.',slices:['Reproduce one offline edit with fictional accounts.','Handle the selected reconnect or account transition.','Prove isolation and add a durable regression check.'],proof:'Prepare a trace and UI recording for a chosen account-switch scenario. Compare queue ownership before and after reconnect.',boundary:'A regression check must fail against the chosen earlier behavior. Do not invent a past incident.',telemetry:'Show only fictional account labels and redacted queue events.',prompts:['Trace queue ownership across offline edits, sign-out and sign-in. Identify the actual contract before proposing a fix.','Choose one account transition to demonstrate. List expected behavior and the smallest reproducible fixture.','Review whether a retry could execute under a different account. Cite the path and reproduce with fictional accounts.']},
 retention: {label:'Tenant-specific retention',tag:'Best backend depth',pitch:'Add a retention setting to a multi-tenant service. A reasonable-looking worker deletes the wrong set of records.',why:'Strong intent and production discussion: cutoff semantics, tenant isolation, dry runs and irreversible effects.',risk:'Needs domain explanation and more backend setup. Deletes and retention policy can overwhelm a general engineering talk.',prep:'Estimate 2 to 3 days for a disposable dataset, frozen clock, dry-run output, regression check and recording.',facts:['Tenants may have different policies.','A worker chooses eligible records.','The cutoff clock must be controlled.','Dry-run selection is observable before deletion.'],decision:'Proposed invariant: the selected set contains only this tenant\'s expired records, with an explicitly agreed cutoff boundary.',exclude:'No legal-retention advice, real deletion, scheduler internals or complete backup system.',slices:['Preview the selected set without deletion.','Apply an agreed policy to disposable records.','Verify tenant and boundary cases with a frozen clock.'],proof:'Show the exact selected IDs for two tenants at the cutoff. A neighboring record stays untouched.',boundary:'Remove the tenant predicate or change the cutoff comparison; the check must fail.',telemetry:'Compare intended and affected record counts. Reverting code does not restore deleted data.',prompts:['Trace how the worker selects records, derives tenant scope and reads the clock. Mark uncertain behavior.','Turn the retention request into exact boundary examples, a dry-run path and explicit exclusions.','Challenge the selection query using a second tenant and one record exactly at the cutoff.']}
};
export const cuts = [
 ['Cut','Model rankings and provider setup','Save 4 to 8 min','They date quickly and do not establish quality. Put links in the appendix.'],
 ['Compress','Your AI workflow history','Cap at 1 min','Use one change in your thinking, not a timeline of tools.'],
 ['Compress','Chopin, Spec Kit and Kiro','Cap at 1 min','One artifact shows the shift toward research and planning. Avoid three product demos.'],
 ['Cut','Ralph / swarm taxonomy','Save 4 to 6 min','Show one working loop and its failure path. Keep the software-factory debate in the comparison.'],
 ['Add','Independent expected result','Inside verification','State the expected boundary behavior before reading the generated test.'],
 ['Add','The stop path','Inside loop demo','Show a stale commit, repeated failure or budget exhaustion, not just success.'],
 ['Add','Team understanding','Inside research / review','Have someone explain the changed behavior without the agent\'s summary.'],
 ['Keep','The counterargument','Protect 4 to 6 min','Small changes are a strong default. They are not a law and human review is not infallible.']
];
