<script setup lang="ts">
import MarkdownScroller from './MarkdownScroller.vue'

const lines = [
  '---',
  'date: "2026-09-05T12:00:00Z"',
  'author: opencode',
  'type: structure-outline',
  'topic: "Cancel an active agent run"',
  'status: draft',
  'related_research: ".opencode/thoughts/rpi/run-cancel/research.md"',
  'related_design: ".opencode/thoughts/rpi/run-cancel/design.md"',
  '---',
  '',
  '# Cancel an active agent run',
  '',
  '## Design Summary',
  '',
  '- A user can cancel a running job from the project view.',
  '- Cancellation is idempotent and ends in an explicit `cancelled` state.',
  '',
  '## Patterns To Follow',
  '',
  '- Command handling: `src/server/runs/retryRun.ts`',
  '- Run actions: `src/ui/run/RunActions.tsx`',
  '',
  '## Phase Outline',
  '',
  '### Phase 1: Cancel one active run end to end',
  '',
  '- Goal: A running job can be cancelled and observed as cancelled.',
  '- Summary: Add the command, API route and project-view action as one slice.',
  '- Why this phase exists now: It proves the full path before hardening it.',
  '',
  '#### File Changes',
  '',
  '- `src/server/runs/cancelRun.ts`: stop the worker and persist `cancelled`.',
  '- `src/api/runs/[runId]/cancel.ts`: expose the idempotent command.',
  '- `src/ui/run/RunActions.tsx`: show Cancel only for active runs.',
  '- `tests/runs/cancelRun.test.ts`: cover running and terminal states.',
  '',
  '#### Validation',
  '',
  '- API test proves repeated cancellation is safe.',
  '- Browser check proves the action disappears and status updates.',
  '- Existing tests, lint, types and build pass.',
  '',
  '#### Phase Boundary',
  '',
  '- Retry, bulk cancellation and history filtering stay out.',
  '',
  '### Phase 2: Harden failures and reconnects',
  '',
  '- Goal: Cancellation remains correct when the worker is slow or disconnected.',
  '- File changes: add timeout handling, recovery and visible failure states.',
  '- Validation: exercise delayed acknowledgement and browser reconnect.',
  '',
  '## Risks Or Ordering Notes',
  '',
  '- Confirm whether the worker already exposes an abort signal.',
]

const steps = [
  { at: 0, start: 1, end: 16, label: 'Intent and approved direction' },
  { at: 1, start: 18, end: 21, label: 'Existing patterns with exact file references' },
  { at: 2, start: 25, end: 29, label: 'A slice with a meaningful verification boundary' },
  { at: 3, start: 31, end: 36, label: 'Concrete files and responsibilities' },
  { at: 4, start: 38, end: 45, label: 'Observable validation and explicit exclusions' },
  { at: 5, start: 47, end: 54, label: 'The next slice and unresolved risk' },
]
</script>

<template>
  <MarkdownScroller filename="structure.md" :lines="lines" :steps="steps" />
</template>
